language: java
jdk: openjdk8
branches:
  only:
    - master
sudo: true
before-script:
  - sudo apt-get install cf-cli
script:
  - mvn clean install
after_success:
  - cf login -a https://api.run.pivotal.io -u $USERNAME -p $PASSWORD -o AnimeRepo -s development
  - cf push anime-repo -p target/animerepo-0.0.1-SNAPSHOT.jar