language: java
jdk: openjdk8
branches:
  only:
    - master
sudo: true
install:
  - mvn -N io.takari:maven:wrapper
deploy:
   provider: cloudfoundry
   username: $USERNAME
   password: $PASSWORD
   api: https://api.run.pivotal.io
   organization: AnimeRepo
   space: development
   app_name: anime-repo
   on: 
    repo: Kiran3232/AnimeRepoBackEnd