language: java
jdk: openjdk8
branches:
  only:
    - master
sudo: true
install:
  - mvn -N io.takari:maven:wrapper
before-script:
  - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
  - echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
  - sudo apt-get update
  - sudo apt-get install cf-cli
script:
  - mvn clean install
  - mvn verify sonar:sonar
after_success:
  - cf login -a https://api.run.pivotal.io -u $USERNAME -p $PASSWORD -o AnimeRepo -s development
  - cf push anime-repo -p target/animerepo-0.0.1-SNAPSHOT.jar