language: java
jdk: openjdk8
branches:
  only:
    - master
sudo: true
install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
   provider: cloudfoundry
   username: $USERNAME
   password: $PASSWORD
   api: https://api.run.pivotal.io
   organization: AnimeRepo
   space: development