language: java
jdk: oraclejdk8
branches:
  only:
    - master
sudo: true
deploy:
   provider: cloudfoundry
   username: $USERNAME
   password: $PASSWORD
   api: https://api.run.pivotal.io
   organization: AnimeRepo
   space: development